<?xml version="1.0" encoding="iso-8859-1"?>

<!-- the dtd describing an athlet entity -->
<!DOCTYPE athlet [
	<!ELEMENT athlet (firstname,
			  lastname,
			  gender,
			  birthday,
			  weight?,
			  height?,
			  runningfreq?,
			  avgdist?,
			  kmtime5?,
			  kmtime10?,
			  biggestdist?,
			  avgpulse?,
			  morningpulse?
	)>
	<!ATTLIST athlet version CDATA #REQUIRED>
		<!ELEMENT firstname (#PCDATA)>
		<!ELEMENT lastname (#PCDATA)>
           <!ELEMENT gender EMPTY>
           <!ATTLIST gender value (female | male) #REQUIRED>
		<!ELEMENT birthday (#PCDATA)>
		<!ELEMENT weight (#PCDATA)>
		<!ELEMENT height (#PCDATA)>
		<!ELEMENT runningfreq (#PCDATA)>
		<!ELEMENT avgdist (#PCDATA)>
		<!ELEMENT kmtime5 (#PCDATA)>
		<!ELEMENT kmtime10 (#PCDATA)>
		<!ELEMENT biggestdist (#PCDATA)>
		<!ELEMENT avgpulse (#PCDATA)>
		<!ELEMENT morningpulse (#PCDATA)>
]>
<athlet version="1.0">
	<firstname>Falco</firstname>
	<lastname>Hirschenberger</lastname>
	<gender value="male"/>
	<birthday>1978-07-06</birthday>
	<weight>75</weight>
	<height>178</height>
	<runningfreq>4</runningfreq>
	<avgpulse>160</avgpulse>
	<avgdist>5000</avgdist>
	<kmtime5>00:30:00</kmtime5>
	<kmtime10>00:53:00</kmtime10>
	<biggestdist>22000</biggestdist>
	<morningpulse>55</morningpulse>
</athlet>
